export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const UPDATE_POSTS_SCORE = "UPDATE_POSTS_SCORE";
export const UPDATE_POST_COMMENTS = "UPDATE_POST_COMMENTS";

export const POST_DETAILS_LOADED = "POST_DETAILS_LOADED";
export const UPDATE_COMMENT_SCORE = "UPDATE_COMMENT_SCORE";

export const TOGGLE_COMMENT_EDIT = "TOGGLE_COMMENT_EDIT";

export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";

export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";